setwd('/ebio/abt6_projects9/Methylome_variation_HPG1/newOrigins/post_vcf1/shapeit/for762_eachCluster5/finestructure/nAm/admixtools')
fst <- as.matrix(read.table('762_eachCluster5noDup.nAmWGS.nAm.phylip', head=F, row.names = 1))
head(fst)
library(ggplot2)
library(reshape2)
library(ape)
tree <- nj(as.dist(fst))
unrooted_tree <- plot(unroot(tree), type= "unrooted",edge.width = 4, cex=1)
rooted_tree <- plot(root(tree, "group10", resolve.root = T), edge.width = 0.5, cex=1)
dev.off()
